language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'leap-analyticx' ]; then cd .. && eval "mv $currentfolder leap-analyticx" && cd leap-analyticx; fi