language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
before_script:
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y build-essential
  - npm install -g bower
  - npm install phantomjs
  - npm install -g karma
  - bower install
  - grunt build